name: 30082025
version: '1.0-SNAPSHOT'
main: com.whirdle.threethousandeight.threethousandeight
api-version: '1.21'
commands:
  attribute:
    aliases: [att, attb]
    usage: /attribute <attribute> [value]
  saveattribute:
    aliases: [patt, pattb, presetattribute, presetattb]
  reloadattribute:
    permission: 30082025.reload